services:
  chrome:
    image: selenium/standalone-chrome
    container_name: chrome

  django:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: mac_menu_django
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command:
      - bash
      - -c
      - "./manage.py collectstatic --noinput && ./manage.py migrate && ./manage.py runserver '0.0.0.0:8001'"
    depends_on:
     - chrome
volumes:
  static_volume:
  media_volume:


